on:
  push:
    branches:
      - main

jobs:
  sync_fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add upstream remote
        run: git remote add upstream https://github.com/PiesArentSquare/csc380-team-e-gdl.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes into main
        run: |
          git checkout main
          git merge upstream/main --no-edit

      - name: Push changes to fork
        run: git push origin main



