name: Build GWAT
on: [push]
jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - run: |
          chmod +x build.sh
          ${{ github.workspace }}/build.sh
      - run: ls ${{ github.workspace }}
