name: Build GWAT
on: [push]
jobs:
  build:
    name: Build GWAT to executable
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            target: Linux
            cmd: >
              pyinstaller -D src/__init__.py -n gwat-linux -p src/ --copy-metadata numpy --add-data pro/hilbert.pro:pro/hilbert.pro
            filename: gwat-linux
          - os: macos-latest
            target: MacOS
            cmd: >
              pyinstaller -D -w src/__init__.py -n gwat -p src/ --copy-metadata numpy --add-data pro/hilbert.pro:pro/hilbert.pro
            #   cd dist/gwat &&
            #   zip -r9 gwat-macos gwat.app/
            filename: gwat-macos.zip
          - os: windows-latest
            target: Windows
            cmd: >
              pyinstaller -D -w src/__init__.py -n gwat-windows -p src/ --copy-metadata numpy --add-data pro/hilbert.pro:pro/hilbert.pro
            filename: gwat-windows.exe
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Get Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Install Dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Build for ${{ matrix.os }}
        run: ${{ matrix.cmd }}
      - name: Display outputs
        run: ls
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gwat-${{ matrix.os }}
          path: dist/${{ matrix.filename }}
          overwrite: true
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: dist/gwat
          prerelease: false
          replacesArtifacts: true
          commit: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          
        